In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import os 
import tarfile
from six.moves import urllib

In [2]:
def load_csv(path):
    csv_path = os.path.join(path)
    return pd.read_csv(csv_path)

In [3]:
weather_data = load_csv("E:\Labs\AI\Datasets\weatheraus.csv")

In [4]:
weather_data.describe(include="all")

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
count,142193,142193,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132863,132923.000000,132180,...,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,140787,142193.000000,142193
unique,3436,49,NaN,NaN,NaN,NaN,NaN,16,NaN,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2
top,2013-05-13,Canberra,NaN,NaN,NaN,NaN,NaN,W,NaN,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No
freq,49,3418,NaN,NaN,NaN,NaN,NaN,9780,NaN,11393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109332,NaN,110316
mean,NaN,NaN,12.186400,23.226784,2.349974,5.469824,7.624853,NaN,39.984292,NaN,...,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,NaN,2.360682,NaN
std,NaN,NaN,6.403283,7.117618,8.465173,4.188537,3.781525,NaN,13.588801,NaN,...,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,NaN,8.477969,NaN
min,NaN,NaN,-8.500000,-4.800000,0.000000,0.000000,0.000000,NaN,6.000000,NaN,...,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,NaN,0.000000,NaN
25%,NaN,NaN,7.600000,17.900000,0.000000,2.600000,4.900000,NaN,31.000000,NaN,...,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,NaN,0.000000,NaN
50%,NaN,NaN,12.000000,22.600000,0.000000,4.800000,8.500000,NaN,39.000000,NaN,...,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,NaN,0.000000,NaN
75%,NaN,NaN,16.800000,28.200000,0.800000,7.400000,10.600000,NaN,48.000000,NaN,...,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,NaN,0.800000,NaN
max,NaN,NaN,33.900000,48.100000,371.000000,145.000000,14.500000,NaN,135.000000,NaN,...,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,NaN,371.000000,NaN

In [5]:
weather_data.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [6]:
cat_factors = ["Location", "WindGustDir", "WindDir9am", "WindDir3pm"]
bool_factors = ["RainToday", "RainTomorrow"]
date_factors = ["Date"]

In [7]:
for field in bool_factors:
    weather_data[field] = weather_data[field].apply(lambda x : 0. if x == "Yes" else (1. if x == "No" else np.nan))
weather_data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,1.0,0.0,1.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,1.0,0.0,1.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,1.0,0.0,1.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,1.0,1.0,1.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,1.0,0.2,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,1.0,0.0,1.0
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,1.0,0.0,1.0
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,1.0,0.0,1.0
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,1.0,0.0,1.0
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,1.0,0.0,1.0

In [8]:
import time
from datetime import datetime
for field in date_factors:
    weather_data[field] = weather_data[field].apply(lambda x : time.mktime(datetime.strptime(x, "%Y-%m-%d").timetuple()))
weather_data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,1.228079e+09,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,1.0,0.0,1.0
1,1.228165e+09,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,1.0,0.0,1.0
2,1.228252e+09,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,1.0,0.0,1.0
3,1.228338e+09,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,1.0,1.0,1.0
4,1.228424e+09,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,1.0,0.2,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,1.497906e+09,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,1.0,0.0,1.0
142189,1.497992e+09,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,1.0,0.0,1.0
142190,1.498079e+09,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,1.0,0.0,1.0
142191,1.498165e+09,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,1.0,0.0,1.0
142192,1.498252e+09,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,1.0,0.0,1.0

In [9]:
from sklearn.preprocessing import LabelBinarizer
for field in cat_factors:
    encoder = LabelBinarizer()
    hot_cat = encoder.fit_transform(weather_data[field].apply(lambda x : field + '=' + ("Unk" if type(x) != str else x))).astype(float)
    tmp = pd.DataFrame(hot_cat, columns=encoder.classes_)
    weather_data = pd.concat([weather_data, tmp], axis=1)
    weather_data.pop(field)
weather_data

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm=NW,WindDir3pm=S,WindDir3pm=SE,WindDir3pm=SSE,WindDir3pm=SSW,WindDir3pm=SW,WindDir3pm=Unk,WindDir3pm=W,WindDir3pm=WNW,WindDir3pm=WSW
0,1.228079e+09,13.4,22.9,0.6,NaN,NaN,44.0,20.0,24.0,71.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.228165e+09,7.4,25.1,0.0,NaN,NaN,44.0,4.0,22.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.228252e+09,12.9,25.7,0.0,NaN,NaN,46.0,19.0,26.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.228338e+09,9.2,28.0,0.0,NaN,NaN,24.0,11.0,9.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.228424e+09,17.5,32.3,1.0,NaN,NaN,41.0,7.0,20.0,82.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,1.497906e+09,3.5,21.8,0.0,NaN,NaN,31.0,15.0,13.0,59.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142189,1.497992e+09,2.8,23.4,0.0,NaN,NaN,31.0,13.0,11.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142190,1.498079e+09,3.6,25.3,0.0,NaN,NaN,22.0,13.0,9.0,56.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142191,1.498165e+09,5.4,26.9,0.0,NaN,NaN,37.0,9.0,9.0,53.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
142192,1.498252e+09,7.8,27.0,0.0,NaN,NaN,28.0,13.0,7.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
weather_data.dtypes

Date              float64
MinTemp           float64
MaxTemp           float64
Rainfall          float64
Evaporation       float64
                   ...
WindDir3pm=SW     float64
WindDir3pm=Unk    float64
WindDir3pm=W      float64
WindDir3pm=WNW    float64
WindDir3pm=WSW    float64
Length: 120, dtype: object

In [11]:
targets = weather_data["RainTomorrow"]
weather_data = weather_data.drop("RainTomorrow", axis='columns')
bool_factors.remove("RainTomorrow")

In [12]:
min_corr = 0.1
weather_data.corrwith(targets).apply(lambda x : (abs(x), x)).sort_values(ascending=False).apply(lambda x : x[1]).where(lambda x : abs(x) > min_corr).dropna()

RISK_MM         -0.501485
Sunshine         0.450768
Humidity3pm     -0.446160
Cloud3pm        -0.381870
Cloud9am        -0.317380
RainToday        0.313097
Humidity9am     -0.257161
Pressure9am      0.246371
Rainfall        -0.239032
WindGustSpeed   -0.234010
Pressure3pm      0.226031
Temp3pm          0.192424
MaxTemp          0.159237
Evaporation      0.119285
dtype: float64

In [13]:
def print_nans_info(data):
    nans = data.apply(lambda x : x.apply(lambda x : np.isnan(x).astype(int))).agg('sum').sort_values(ascending=False)
    print("total rows:", len(data))
    for field in nans.index:
        if nans[field] == 0:
            break
        print(field, "nans count:", nans[field])

In [14]:
def get_nans_fields(data, ignore_factors=[]):
    nans = data.drop(ignore_factors, axis=1).apply(lambda x : x.apply(lambda x : np.isnan(x).astype(int))).agg('sum')
    return nans.sort_values(ascending=False).where(lambda x : x > 0).dropna()

In [15]:
print_nans_info(weather_data)

total rows: 142193
Sunshine nans count: 67816
Evaporation nans count: 60843
Cloud3pm nans count: 57094
Cloud9am nans count: 53657
Pressure9am nans count: 14014
Pressure3pm nans count: 13981
WindGustSpeed nans count: 9270
Humidity3pm nans count: 3610
Temp3pm nans count: 2726
WindSpeed3pm nans count: 2630
Humidity9am nans count: 1774
Rainfall nans count: 1406
RainToday nans count: 1406
WindSpeed9am nans count: 1348
Temp9am nans count: 904
MinTemp nans count: 637
MaxTemp nans count: 322

In [16]:
def get_valid_pool(data, field):
    not_nan_axis = data.apply(lambda x : True in x.apply(lambda y : np.isnan(y)).values, axis=1).where(lambda x : x == False).dropna().index
    field_nan_axis = data.apply(lambda x : np.isnan(x[field]), axis=1).where(lambda x : x).dropna().index
    return not_nan_axis, field_nan_axis

In [17]:
from sklearn.linear_model import LinearRegression

def train_lr_model(learn, field):
    model = LinearRegression()
    features = learn.drop(field, axis='columns')
    res = learn[field]
    model.fit(features, res)
    return model

In [18]:
from sklearn.impute import SimpleImputer

def apply_model(data, field, model, learn_ind, apply_ind):
    imputer = SimpleImputer(strategy="median")
    
    apply = data.drop(field, axis='columns')
    
    imputer.fit(apply)
    apply = imputer.transform(apply)
    res = model.predict(apply).astype(float)

    for i in apply_ind:
        data[field][i] = res[i]
    
    return data

In [19]:
def repair_float_fields(data, nan_fields):
    for field in nan_fields.index:
        learn_ind, apply_ind = get_valid_pool(data, field)
        model = train_lr_model(data.loc[learn_ind], field)
        data = apply_model(data, field, model, learn_ind, apply_ind)
        print(field, "\tready!")
    return data

In [20]:
nan_fields = get_nans_fields(weather_data, bool_factors)
print(nan_fields)
weather_data = repair_float_fields(weather_data, nan_fields)
weather_data

Sunshine         67816.0
Evaporation      60843.0
Cloud3pm         57094.0
Cloud9am         53657.0
Pressure9am      14014.0
Pressure3pm      13981.0
WindGustSpeed     9270.0
Humidity3pm       3610.0
Temp3pm           2726.0
WindSpeed3pm      2630.0
Humidity9am       1774.0
Rainfall          1406.0
WindSpeed9am      1348.0
Temp9am            904.0
MinTemp            637.0
MaxTemp            322.0
dtype: float64
Sunshine 	ready!
Evaporation 	ready!
Cloud3pm 	ready!
Cloud9am 	ready!
Pressure9am 	ready!
Pressure3pm 	ready!
WindGustSpeed 	ready!
Humidity3pm 	ready!
Temp3pm 	ready!
WindSpeed3pm 	ready!
Humidity9am 	ready!
Rainfall 	ready!
WindSpeed9am 	ready!
Temp9am 	ready!
MinTemp 	ready!
MaxTemp 	ready!

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm=NW,WindDir3pm=S,WindDir3pm=SE,WindDir3pm=SSE,WindDir3pm=SSW,WindDir3pm=SW,WindDir3pm=Unk,WindDir3pm=W,WindDir3pm=WNW,WindDir3pm=WSW
0,1.228079e+09,13.4,22.9,0.6,5.098288,7.245865,44.0,20.0,24.0,71.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.228165e+09,7.4,25.1,0.0,5.207546,8.757433,44.0,4.0,22.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.228252e+09,12.9,25.7,0.0,7.954579,10.576581,46.0,19.0,26.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.228338e+09,9.2,28.0,0.0,6.171537,9.391151,24.0,11.0,9.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.228424e+09,17.5,32.3,1.0,6.178423,5.740262,41.0,7.0,20.0,82.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,1.497906e+09,3.5,21.8,0.0,4.182434,8.016167,31.0,15.0,13.0,59.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142189,1.497992e+09,2.8,23.4,0.0,4.763458,8.515653,31.0,13.0,11.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142190,1.498079e+09,3.6,25.3,0.0,4.155429,8.375748,22.0,13.0,9.0,56.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142191,1.498165e+09,5.4,26.9,0.0,5.120711,8.191633,37.0,9.0,9.0,53.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
142192,1.498252e+09,7.8,27.0,0.0,6.307988,10.602849,28.0,13.0,7.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
print_nans_info(weather_data)

total rows: 142193
RainToday nans count: 1406

In [22]:
from sklearn.ensemble import RandomForestClassifier

def train_rf_model(learn, field):
    model = RandomForestClassifier(n_estimators=500, max_depth=6, n_jobs=-1)
    features = learn.drop(field, axis='columns')
    res = learn[field].astype(bool)
    model.fit(features, res)
    return model

In [23]:
def repair_bool_fields(data, nan_fields):
    for field in nan_fields.index:
        learn_ind, apply_ind = get_valid_pool(data, field)
        model = train_rf_model(data.loc[learn_ind], field)
        data = apply_model(data, field, model, learn_ind, apply_ind)
        print(field, "ready!")
    return data

In [24]:
nan_fields = get_nans_fields(weather_data)
print(nan_fields)
weather_data = repair_bool_fields(weather_data, nan_fields)
weather_data

RainToday    1406.0
dtype: float64
RainToday ready!

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm=NW,WindDir3pm=S,WindDir3pm=SE,WindDir3pm=SSE,WindDir3pm=SSW,WindDir3pm=SW,WindDir3pm=Unk,WindDir3pm=W,WindDir3pm=WNW,WindDir3pm=WSW
0,1.228079e+09,13.4,22.9,0.6,5.098288,7.245865,44.0,20.0,24.0,71.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.228165e+09,7.4,25.1,0.0,5.207546,8.757433,44.0,4.0,22.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.228252e+09,12.9,25.7,0.0,7.954579,10.576581,46.0,19.0,26.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.228338e+09,9.2,28.0,0.0,6.171537,9.391151,24.0,11.0,9.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.228424e+09,17.5,32.3,1.0,6.178423,5.740262,41.0,7.0,20.0,82.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,1.497906e+09,3.5,21.8,0.0,4.182434,8.016167,31.0,15.0,13.0,59.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142189,1.497992e+09,2.8,23.4,0.0,4.763458,8.515653,31.0,13.0,11.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142190,1.498079e+09,3.6,25.3,0.0,4.155429,8.375748,22.0,13.0,9.0,56.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142191,1.498165e+09,5.4,26.9,0.0,5.120711,8.191633,37.0,9.0,9.0,53.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
142192,1.498252e+09,7.8,27.0,0.0,6.307988,10.602849,28.0,13.0,7.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
weather_data.describe(include="all")

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm=NW,WindDir3pm=S,WindDir3pm=SE,WindDir3pm=SSE,WindDir3pm=SSW,WindDir3pm=SW,WindDir3pm=Unk,WindDir3pm=W,WindDir3pm=WNW,WindDir3pm=WSW
count,1.421930e+05,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,...,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000,142193.000000
mean,1.364765e+09,12.187409,23.227010,2.341504,5.108376,7.170861,39.855621,13.943172,18.476383,68.816197,...,0.059553,0.067500,0.074990,0.064293,0.056332,0.064574,0.026570,0.069701,0.060875,0.065608
std,7.968098e+07,6.394735,7.112601,8.431952,3.766638,3.230719,13.446536,8.883476,8.818644,19.074735,...,0.236657,0.250886,0.263376,0.245275,0.230562,0.245774,0.160822,0.254643,0.239102,0.247597
min,1.193864e+09,-8.500000,-4.800000,-5.436441,-6.963911,-4.506974,6.000000,-10.383758,-4.322043,-20.906701,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.294261e+09,7.600000,17.900000,0.000000,2.600000,5.116508,31.000000,7.000000,13.000000,57.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.369602e+09,12.000000,22.600000,0.000000,4.701768,7.243476,39.000000,13.000000,17.000000,70.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.434056e+09,16.800000,28.200000,0.800000,7.000000,9.600000,48.000000,19.000000,24.000000,83.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.498338e+09,33.900000,48.100000,371.000000,145.000000,17.658447,135.000000,130.000000,87.000000,118.236880,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [26]:
print_nans_info(weather_data)

total rows: 142193

In [27]:
corr_fields = weather_data.corrwith(targets).apply(lambda x : (abs(x), x)).sort_values(ascending=False).apply(lambda x : x[1]).where(lambda x : abs(x) > min_corr).dropna()
print(corr_fields)

RISK_MM         -0.501485
Humidity3pm     -0.433057
Sunshine         0.422801
Cloud3pm        -0.364767
RainToday        0.317176
Cloud9am        -0.310841
Humidity9am     -0.253466
Rainfall        -0.238142
Pressure9am      0.237195
WindGustSpeed   -0.226882
Pressure3pm      0.215718
Temp3pm          0.192713
MaxTemp          0.159287
Evaporation      0.119743
dtype: float64

In [28]:
trunc_data = pd.concat([weather_data[corr_fields.index], targets], axis=1)
trunc_data.to_csv('E:\Labs\AI\Datasets\weather_ready_trunc.csv')

full_data = pd.concat([weather_data, targets], axis=1)
full_data.to_csv('E:\Labs\AI\Datasets\weather_ready_full.csv')